[package]
name = "cploit"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
tokio = { version = "*", features = ["full"] }
reqwest = { version = "*", features = ["rustls-tls"] }
rand = "0.8.5"
colored = "3.0.0"
regex = "1.11.1"
scraper = "0.23.1"
