[package]
name = "ripai"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
html-escape = "0.2.13"
html5ever = "0.31.0"
markup5ever_rcdom = "0.3.0"
regex = "1.11.1"
reqwest = "*"
scraper = "0.23.1"
tokio = { version = "*", features = ["full"] }
urlencoding = "2.1.3"
