[package]
name = "ripai"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
reqwest = { version = "*", features = ["json"] }
tokio = { version = "*", features = ["full"] }
urlencoding = "2.1.3"
futures = "*"
url = "*"
clap = { version = "*", features = ["derive"] }

