torch:
	cd /root && wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.6.0%2Bcpu.zip && unzip libtorch*.zip && rm libtorch*.zip
	echo 'export LIBTORCH=/root/libtorch' >> ~/.bashrc && source ~/.bashrc