torch:
   cd /root
   wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.6.0%2Bcpu.zip
   unzip libtorch-shared-with-deps-2.6.0%2Bcpu.zip
   rm libtorch-shared-with-deps-2.6.0%2Bcpu.zip
   sudo ln -s /root/libtorch/include /usr/local/include/libtorch
   sudo ln -s /root/libtorch/lib /usr/local/lib/libtorch
